### ISSUE TITLE
Expected all tensors to be on the same device, but found at least two devices cpu and cuda 

### ISSUE THREAD

**Issue by kdrkdrkdr** [StarxSky/tacotron2-JP#1]
![image](https://user-images.githubusercontent.com/49074597/188045395-f3b1f9cb-00f6-4dfa-9b84-ac8ade0aac93.png)

![image](https://user-images.githubusercontent.com/49074597/188045353-c2ebf455-613e-4de8-b1bf-f30a39bc360b.png)

When I infer this code, This Error Occured.. How to solve this problem?
How many steps did you take until demo.wav came out?

**Comment by StarxSky** [comment]
Hello, for this problem, please check whether the model is placed on the right device and pay special attention to the model.to() method

**Comment by StarxSky** [comment]
Please keep the equipment where the model is placed consistent

**Comment by StarxSky** [comment]
The problem has been fixed
thanks !

**Comment by kdrkdrkdr** [comment]
The problem has not been resolved. Could you check the conference file again?

**Comment by kdrkdrkdr** [comment]
Let me ask you one more question.
How many epochs did you learn for the ayachi_nene model?

**Comment by StarxSky** [comment]
sorry! l don't know, beacuse the pre-trained models was other people trained. [tacotron2-Japanese] the repos



| |
***@***.***
|
|
***@***.***
|




---- Replied mail ----
| From | Sleeping ***@***.***> |
| Date | 09/20/2022 17:34 |
| To | ***@***.***> |
| Cc | ***@***.***>、State ***@***.***> |
| Subject | Re: [StarxSky/tacotron2-JP] Expected all tensors to be on the same device, but found at least two devices cpu and cuda (Issue #1) |

Let me ask you one more question.
How many epochs did you learn for the ayachi_nene model?

**Comment by kdrkdrkdr** [comment]
The problem not fixed.. please check the inference file.. Did you push the file properly?

**Comment by StarxSky** [comment]
but the code run normal on my PC.



| |
***@***.***
|
|
***@***.***
|




---- Replied mail ----
| From | Sleeping ***@***.***> |
| Date | 10/04/2022 07:42 |
| To | ***@***.***> |
| Cc | ***@***.***>、State ***@***.***> |
| Subject | Re: [StarxSky/tacotron2-JP] Expected all tensors to be on the same device, but found at least two devices cpu and cuda (Issue #1) |

The problem not fixed.. please check the inference file.. Did you push the file properly?
